const drinks = [
  {
    name: "Pepsi / Pepsi max",
    price: 2.05,
    amount: 0.25,
    type: "soft",
  },
  {
    name: "Mirinda",
    price: 2.05,
    amount: 0.25,
    type: "soft",
  },
  {
    name: "7 UP",
    price: 2.05,
    amount: 0.25,
    type: "soft",
  },
  {
    name: "Tonic",
    price: 2.05,
    amount: 0.25,
    type: "soft",
  },
  {
    name: "Canada dry",
    price: 2.05,
    amount: 0.25,
    type: "soft",
  },
  {
    name: "Crodino",
    price: 2.67,
    amount: 0.1,
    type: "soft",
  },
  {
    name: "Mattoni - still, lightly sparkling",
    price: 1.84,
    amount: 0.33,
    type: "soft",
  },
  {
    name: "Juice - daily offer",
    price: 2.05,
    amount: 0.3,
    type: "soft",
  },
  {
    name: "Soda",
    price: 0.61,
    amount: 0.1,
    type: "soft",
  },
  {
    name: "Filtered water / with citrus and mint",
    price: 1.64,
    amount: 0.5,
    type: "soft",
  },
  {
    name: "Filtered water / with citrus and mint",
    price: 2.46,
    amount: 1,
    type: "soft",
  },
  {
    name: "Raspberry with lime",
    price: 3.28,
    amount: 0.4,
    type: "lemonade",
  },
  {
    name: "Grapefruit with elderberry",
    price: 3.28,
    amount: 0.4,
    type: "lemonade",
  },
  {
    name: "Mango with passion fruit",
    price: 3.28,
    amount: 0.4,
    type: "lemonade",
  },
  {
    name: "Dragon fruit",
    price: 3.28,
    amount: 0.4,
    type: "lemonade",
  },
  {
    name: "Budvar 33",
    price: 2.67,
    amount: 0.5,
    type: "beer",
  },
  {
    name: "Budvar 33",
    price: 1.73,
    amount: 0.3,
    type: "beer",
  },
  {
    name: "Budvar Non-Alcoholic Draught",
    price: 2.27,
    amount: 0.5,
    type: "beer",
  },
  {
    name: "Budvar Non-Alcoholic Draught",
    price: 1.45,
    amount: 0.3,
    type: "beer",
  },
  {
    name: "Radler Draught - 7 UP, Budvar 33",
    price: 3.13,
    amount: 0.5,
    type: "beer",
  },
  {
    name: "Pilsner Urquell Bottled",
    price: 2.67,
    amount: 0.5,
    type: "beer",
  },
  {
    name: "Ristretto",
    price: 2.49,
    amount: 0.02,
    type: "coffee",
  },
  {
    name: "Espresso",
    price: 2.49,
    amount: 0.03,
    type: "coffee",
  },
  {
    name: "Espresso macchiato",
    price: 2.49,
    amount: 0.03,
    type: "coffee",
  },
  {
    name: "Espresso doppio",
    price: 3.82,
    amount: 0.06,
    type: "coffee",
  },
  {
    name: "Espresso lungo",
    price: 2.49,
    amount: 0.09,
    type: "coffee",
  },
  {
    name: "Cafe americano",
    price: 2.49,
    amount: 0.2,
    type: "coffee",
  },
  {
    name: "Cappuccino",
    price: 3.28,
    amount: 0.2,
    type: "coffee",
  },
  {
    name: "Latte macchiato",
    price: 3.28,
    amount: 0.2,
    type: "coffee",
  },
  {
    name: "Flat white",
    price: 4.12,
    amount: 0.2,
    type: "coffee",
  },
  {
    name: "Iced coffee - vanilla ice cream, whipped cream",
    price: 4.12,
    amount: 0.3,
    type: "coffee",
  },
  {
    name: "Hot chocolate with whipped cream",
    price: 3.27,
    amount: 0.2,
    type: "hot drink",
  },
  {
    name: "Tea (daily offer)",
    price: 2.67,
    amount: 0.004,
    type: "hot drink",
  },
  {
    name: "Fresh ginger tea",
    price: 3.27,
    amount: 0.4,
    type: "hot drink",
  },
  {
    name: "Fresh mint tea",
    price: 3.27,
    amount: 0.4,
    type: "hot drink",
  },
  {
    name: "Mulled wine",
    price: 3.74,
    amount: 0.2,
    type: "hot drink",
  },
  {
    name: "Havana Club Añejo 3 Años, Cuba",
    price: 3.13,
    amount: 0.04,
    type: "rum",
  },
  {
    name: "Legendario Elixír De Cuba 7 y.o., Cuba",
    price: 3.77,
    amount: 0.04,
    type: "rum",
  },
  {
    name: "Republica Exclusive, Czech Republic",
    price: 3.47,
    amount: 0.04,
    type: "rum",
  },
  {
    name: "Don Papa, Philippines",
    price: 5.36,
    amount: 0.04,
    type: "rum",
  },
  {
    name: "Diplomatico, Reserva Exclusiva, Venezuela",
    price: 5.51,
    amount: 0.04,
    type: "rum",
  },
  {
    name: "Zacapa 23 Centenario, Guatemala",
    price: 5.87,
    amount: 0.04,
    type: "rum",
  },
  {
    name: "Kirk & Sweeney, 23 years, Dominican Republic",
    price: 7.32,
    amount: 0.04,
    type: "rum",
  },
  {
    name: "Jameson",
    price: 3.47,
    amount: 0.04,
    type: "whiskey",
  },
  {
    name: "Johnnie Walker Red",
    price: 3.47,
    amount: 0.04,
    type: "whiskey",
  },
  {
    name: "Jack Daniel's / Honey",
    price: 4.14,
    amount: 0.04,
    type: "whiskey",
  },
  {
    name: "Glenmorangie 10 Years Old",
    price: 5.36,
    amount: 0.04,
    type: "whiskey",
  },
  {
    name: "Lagavulin Single Malt 16y",
    price: 6.91,
    amount: 0.02,
    type: "whiskey",
  },
  {
    name: "Reviseur XO, Champagne, France",
    price: 7.32,
    amount: 0.02,
    type: "cognac",
  },
  {
    name: "Campari",
    price: 2.43,
    amount: 0.04,
    type: "liqueur",
  },
  {
    name: "Martini Bianco / Dry",
    price: 2.83,
    amount: 0.08,
    type: "liqueur",
  },
  {
    name: "Jägermeister",
    price: 3.13,
    amount: 0.04,
    type: "liqueur",
  },
  {
    name: "Becherovka",
    price: 2.67,
    amount: 0.04,
    type: "liqueur",
  },
  {
    name: "Fernet Stock",
    price: 2.67,
    amount: 0.04,
    type: "liqueur",
  },
  {
    name: "Vodka Finlandia",
    price: 3.13,
    amount: 0.04,
    type: "spirit",
  },
  {
    name: "Slivovice / Williams Pear",
    price: 3.4,
    amount: 0.04,
    type: "spirit",
  },
  {
    name: "Malinovice Martenz",
    price: 5.65,
    amount: 0.04,
    type: "spirit",
  },
  {
    name: "Gin Beefeater",
    price: 2.83,
    amount: 0.04,
    type: "spirit",
  },
  {
    name: "Grappa Pircher",
    price: 4.14,
    amount: 0.04,
    type: "spirit",
  },
  {
    name: "Portal Fine Ruby Porto",
    price: 4.14,
    amount: 0.04,
    type: "spirit",
  },
  {
    name: "Portal Six Barrels, Tawny Reserve Porto",
    price: 4.14,
    amount: 0.04,
    type: "spirit",
  },
  {
    name: "Hugo",
    price: 4.89,
    amount: 0.2,
    type: "mixed drink",
  },
  {
    name: "Mimosa",
    price: 4.93,
    amount: 0.2,
    type: "mixed drink",
  },
  {
    name: "Aperol Spritz",
    price: 5.5,
    amount: 0.14,
    type: "mixed drink",
  },
  {
    name: "Peach Spritz",
    price: 4.89,
    amount: 0.2,
    type: "mixed drink",
  },
  {
    name: "Strawberry Spritz",
    price: 4.89,
    amount: 0.2,
    type: "mixed drink",
  },
  {
    name: "Piña Colada",
    price: 5.66,
    amount: 0.14,
    type: "mixed drink",
  },
  {
    name: "Vodka & Juice",
    price: 5.5,
    amount: 0.24,
    type: "mixed drink",
  },
  {
    name: "Cuba Libre",
    price: 5.5,
    amount: 0.24,
    type: "mixed drink",
  },
  {
    name: "Gin Tonic",
    price: 5.5,
    amount: 0.24,
    type: "mixed drink",
  },
  {
    name: "Mojito",
    price: 5.66,
    amount: 0.14,
    type: "mixed drink",
  },
  {
    name: "Virgin Mojito",
    price: 4.89,
    amount: 0.2,
    type: "mixed drink",
  },
  {
    name: "Virgin Colada",
    price: 4.89,
    amount: 0.15,
    type: "mixed drink",
  },
];

export default drinks;
