const meals = [
  {
    name: "Chicken Supreme, Pumpkin Puree, Grilled Vegetables",
    price: 12.1,
    grammage: 200,
    image: null,
    alergens: [7, 12],
    type: "main",
  },
  {
    name: "0.3L Kulajda with Poached Egg",
    price: 3.1,
    grammage: 300,
    image:
      "https://s3-prague.stor.geetoo.com/nejendvorek/production/public/w500h5007RKUH2udeqGINmUyEGBQkSrsBAIUcmwFxYBU2wow.jpg",
    alergens: [1, 3, 7, 9],
    type: "soup",
  },
  {
    _id: "670acf73387de1b0223b61e2",
    name: "Duck Breast, Red Cabbage Puree, Homemade Croquettes, Plum Sauce",
    price: 14.4,
    grammage: 200,
    image: null,
    alergens: [1, 3, 7, 9, 12],
    type: "main",
  },
  {
    name: "Veal Tartare, Shallots, Capers, Cornichons, Grainy Mustard Mayonnaise, Gran Moravia, Fries",
    price: 9.1,
    grammage: 100,
    image: null,
    alergens: [3, 7, 10, 12],
    type: "starter",
  },
  {
    name: "Slow-Cooked Veal Leg with Herbs, Mashed Potatoes, Shallots",
    price: 14.6,
    grammage: 200,
    image: null,
    alergens: [1, 7, 12],
    type: "main",
  },
  {
    name: "Fresh Spaghetti with Sun-Dried Tomatoes, Garlic, Baby Spinach, Pesto, Parmesan",
    price: 11.1,
    grammage: 400,
    image:
      "https://s3-prague.stor.geetoo.com/nejendvorek/production/public/w500h5004cEdZLQolrOwSXcxjX9hPQpO5aK0u8KXjjg7TjRI.jpg",
    alergens: [1, 3, 7],
    type: "main",
  },
  {
    _id: "670acf73387de1b0223b61ed",
    name: "Chocolate Fondant, Crumble, Cherry Sorbet",
    price: 7.2,
    grammage: 80,
    image: null,
    alergens: [1, 3, 7],
    type: "dessert",
  },
  {
    name: "Sorbet as per the offer",
    price: 1.8,
    grammage: null,
    image: null,
    alergens: null,
    type: "dessert",
  },
  {
    name: "Pork 'Tomahawk' Steak, Roasted Potatoes, Bacon, Onions, Cheddar Dip",
    price: 16.5,
    grammage: 400,
    image:
      "https://s3-prague.stor.geetoo.com/nejendvorek/production/public/w500h500uhIeGdN7xxHuv0DmvyoqEDOQJjjKLS0SUj35uKEp.jpg",
    alergens: [7, 12],
    type: "main",
  },
  {
    name: "Chuck-Roll Burger, Cheddar, Bacon, Caramelized Onions, Roasted Pepper Mayonnaise, Pickles, Iceberg Lettuce, Tomato, Onion Bun, Fries",
    price: 14.6,
    grammage: 150,
    image:
      "https://s3-prague.stor.geetoo.com/nejendvorek/production/public/w500h500FrJBsZj0ZCs5FSWDb0HOjvIOunQADDLt4ia6ySiT.jpg",
    alergens: [1, 3, 7, 10, 11, 12],
    type: "main",
  },
  {
    name: "Caesar Salad with Chicken, Herb Croutons, Crispy Bacon, Capers, Parmesan",
    price: 11.6,
    grammage: 400,
    image:
      "https://s3-prague.stor.geetoo.com/nejendvorek/production/public/w500h5000YaUiDQHefJqkMox6Xpp4iYLPKBVORHvawJ0EUxE.jpg",
    alergens: [1, 3, 4, 7, 10, 12],
    type: "main",
  },
  {
    name: "Crème Brûlée with Tonka Bean and Vanilla Ice Cream",
    price: 7.2,
    grammage: 80,
    image: null,
    alergens: [3, 7, 8],
    type: "dessert",
  },
  {
    name: "Focaccia with Pesto",
    price: 1.8,
    grammage: null,
    image: null,
    alergens: [1, 7, 12],
    type: "bread",
  },
  {
    name: "Whipped Goat Cheese, Marinated Plums, Pear Chutney, Pecans, Focaccia",
    price: 8.4,
    grammage: 80,
    image:
      "https://s3-prague.stor.geetoo.com/nejendvorek/production/public/w500h500kZDkAk0Xc1K8YGvWZfce6OBKXqAft3ypkf3UUwiO.jpg",
    alergens: [1, 7, 8, 12],
    type: "starter",
  },
  {
    name: "Duck Rillettes, Cranberries, Sourdough Bread",
    price: 8.4,
    grammage: 80,
    image: null,
    alergens: [1, 12],
    type: "starter",
  },
  {
    name: "Pork Tenderloin, Pear Chutney, Grenaille, Jus",
    price: 13.3,
    grammage: 200,
    image:
      "https://s3-prague.stor.geetoo.com/nejendvorek/production/public/w500h500S92n6FI66G0MChzzmQsqAGXX5bxoxd6cQF19DX3O.jpg",
    alergens: [9, 12],
    type: "main",
  },
  {
    name: "Pork Ribs in Our Marinade, Toasted Sourdough Bread, Our Pickles",
    price: 13.3,
    grammage: 450,
    image:
      "https://s3-prague.stor.geetoo.com/nejendvorek/production/public/w500h50014pk6ODyNXxzwQ00qxdsRFKzc8IdxYk2tHq47Fad.jpg",
    alergens: [1, 6, 10],
    type: "main",
  },
  {
    name: "Beef Carpaccio, Pesto, Gran Moravia, Arugula, Focaccia",
    price: 9.1,
    grammage: 80,
    image:
      "https://s3-prague.stor.geetoo.com/nejendvorek/production/public/w500h500kZDkAk0Xc1K8YGvWZfce6OBKXqAft3ypkf3UUwiO.jpg",
    alergens: [1, 7, 12],
    type: "starter",
  },
  {
    name: "Caesar Salad with Shrimp, Herb Croutons, Crispy Bacon, Capers, Parmesan",
    price: 12.1,
    grammage: 400,
    image:
      "https://s3-prague.stor.geetoo.com/nejendvorek/production/public/w500h500v7GBqjBflPBzn0HV8Tlrf0RhkLqKCC6MUvZQ1kCj.jpg",
    alergens: [1, 2, 3, 4, 7, 10, 12],
    type: "main",
  },
  {
    name: "Toasted Sourdough Bread",
    price: 1.8,
    grammage: null,
    image: null,
    alergens: [1],
    type: "bread",
  },
  {
    name: "Fresh Spaghetti, Pork Tenderloin, Sun-Dried Tomatoes, Baby Spinach, Pesto, Garlic, Parmesan",
    price: 12.1,
    grammage: 400,
    image:
      "https://s3-prague.stor.geetoo.com/nejendvorek/production/public/w500h500ottzrzrZbVkW5whryiglDYLm0gieykiWnSAIDZRQ.jpg",
    alergens: [1, 3, 7, 9, 12],
    type: "main",
  },
  {
    name: "Grilled Goat Cheese, Salad Leaves, Roasted Root Vegetables, Beetroot, Pecans, Sun-Dried Tomato Pesto",
    price: 11.6,
    grammage: 400,
    image: null,
    alergens: [1, 7, 10, 12],
    type: "main",
  },
  {
    name: "Vanilla Ice Cream",
    price: 1.8,
    grammage: 40,
    image: null,
    alergens: [3, 7, 8],
    type: "dessert",
  },
];

export default meals;
